version: "2"
run:
  tests: true
linters:
  enable:
    - gosec
    - revive
  disable:
    - depguard
  settings:
    gosec:
      severity: medium
      confidence: medium
  exclusions:
    generated: lax
    rules:
      - linters:
          - gosec
        path: js_compare_test.go
        text: G204
      - linters:
          - gosec
        path: property_jsondiffgo_test.go
        text: G404
      - path: (.+)\.go$
        text: '^G104: '
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
